Refactor website to use Hugo and Docsy; Add a blog
serverlessworkflow/serverlessworkflow.github.io pull request #202
Opened 2024-06-07 18:29 UTC by ricardozanini

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
- Fix #199 
- Fix #198 
- Fix #196

**Special notes for reviewers**:
Still, work todo:

- [ ] Add CI to preview the changes on Netlify
- [ ] Add schemas from previous version and 1.0.0-*

**Additional information (if needed):**

2024-06-07 18:50 UTC, cdavernas approved these changes

2024-06-07 18:50 UTC, cdavernas commented
LGTM! Many thanks man ❤️

2024-06-15 14:39 UTC, cdavernas requested changes
Aside from the ordering comment, I think we should re-add the sponsors section, both in the website and the spec.

Even though Neuroglia is for now the only sponsor of the project (and as part of the latter I'm therefore biased), it did sponsor the project, and should therefore clearly appear as such, which also might incentivise others to move in.

We should also add a "buy us a coffe" kind of button, on both website and spec. Donators should also be visibly and explicitly thanked for their donations, and be tracked somewhere in the repo. The money we obtain should be invested for marketing and communication purpose, in other to grow our user base and widen adoption for the further stage of SW in the CNCF.

2024-06-15 14:39 UTC, cdavernas commented on content/en/_index.md
> +
We should always order aphabetically IMHO, so that we avoid opiniated - therefore discussable - ordering in this kind of cases 😉

2024-06-15 14:39 UTC, cdavernas commented on content/en/_index.md
> +
Same comment about ordering.

2024-06-17 16:16 UTC, ricardozanini commented
@cdavernas can you take another review?

2024-06-17 18:14 UTC, cdavernas requested changes
Looks great to me, many thanks!
Do you think you could display the other key features on the index, and provide small code snippets, like now?

2024-06-17 19:43 UTC, ricardozanini commented
> Looks great to me, many thanks! Do you think you could display the other key features on the index, and provide small code snippets, like now?

I would need help with HTML + js to be able to use this: https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes

It appears, but breaks the page. I think it's not meant to be used this way. So maybe @JBBianchi could help in a future PR? I will take a lot of time to do it, which I don't have atm.

What other key features you mean?

2024-06-18 08:24 UTC, JBBianchi commented
> > Looks great to me, many thanks! Do you think you could display the other key features on the index, and provide small code snippets, like now?
> 
> I would need help with HTML + js to be able to use this: https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes
> 
> It appears, but breaks the page. I think it's not meant to be used on the landing page. So maybe @JBBianchi could help in a future PR? I will take a lot of time to do it, which I don't have atm.
> 
> What other key features you mean?

Sure, we can have a look together.

2024-06-18 08:34 UTC, cdavernas commented
> What other key features you mean?

![image](https://github.com/serverlessworkflow/serverlessworkflow.github.io/assets/16137162/4c193ff2-a4ef-476f-b4ec-eb265dd44a0b)

We have a lot more of those in the Readme:

> - Easy to Use: Designed for universal understanding, Serverless Workflow DSL enables users to quickly grasp workflow concepts and create complex workflows effortlessly.
> - Event Driven: Seamlessly integrate events into workflows with support for various formats, including CloudEvents, allowing for event-driven workflow architectures.
> - Service Oriented: The Serverless Workflow DSL empowers developers to seamlessly integrate with service-oriented architectures, allowing them to define workflows that interact with various services over standard application protocols like HTTP, GRPC, OpenAPI, AxsyncAPI, and more.
> - FaaS Centric: Seamlessly invoke functions hosted on various platforms within workflows, promoting a function-as-a-service (FaaS) paradigm and enabling microservices architectures.
> - Timely: Define timeouts for workflows and tasks to manage execution duration effectively.
> - Fault Tolerant: Easily define error handling strategies to manage and recover from errors that may occur during workflow execution, ensuring robustness and reliability.
> - Schedulable: Schedule workflows using CRON expressions or trigger them based on events, providing control over workflow execution timing.
> - Interoperable: Integrates seamlessly with different services and resources.
> - Robust: Offers features such as conditional branching, event handling, and looping constructs.
> - Scalable: Promotes code reusability, maintainability, and scalability across different environments.

And possibly even others worth mentioning...

2024-06-18 16:07 UTC, cdavernas commented
@ricardozanini Yeah, you are right. Maybe 3 more indeed

2024-06-24 17:50 UTC, cdavernas commented
Let's pick the 6 first, no? They feel like the most compelling to me.

2024-06-24 19:28 UTC, ricardozanini commented
@cdavernas if you're happy with the content now, feel free to merge :)

2024-06-24 19:32 UTC, ricardozanini commented
@JBBianchi @cdavernas btw I created an issue to track the code section: https://github.com/serverlessworkflow/serverlessworkflow.github.io/issues/203

2024-06-24 19:35 UTC, ricardozanini commented
@cdavernas one last thing: I've added the schema to the `schemas` section with both YAML and JSON versions. 👍

2024-06-26 18:58 UTC, cdavernas approved these changes

2024-06-27 12:07 UTC, merged